import type { Job } from "./types";

export const SEED_JOBS: Job[] = [
  {
    id: 1,
    company: "Northwind Labs",
    role: "Senior Product Designer",
    status: "Final",
    location: "Seattle, WA",
    workMode: "Hybrid",
    date: "2026-09-12",
    salary: "$150k–175k",
    link: "https://example.com",
    description:
      "Lead design for the analytics suite. Partner with PM and engineering on roadmap, run research, and own the end-to-end experience.",
    notes: "Portfolio review went well. Panel round next Thursday.",
    lat: 47.6062,
    lon: -122.3321,
  },
  {
    id: 2,
    company: "Brightline",
    role: "UX Designer",
    status: "Applied",
    location: "Austin, TX",
    workMode: "On-site",
    date: "2026-09-25",
    salary: "$115k–130k",
    link: "https://example.com",
    description:
      "Design flows for a consumer booking app. 3+ years experience, strong prototyping skills.",
    notes: "",
    lat: 30.2672,
    lon: -97.7431,
  },
  {
    id: 3,
    company: "Fieldnote",
    role: "Product Designer",
    status: "Offer",
    location: "Denver, CO",
    workMode: "Hybrid",
    date: "2026-08-30",
    salary: "$140k",
    link: "",
    description: "Own the mobile experience for a field-research tool used by scientists.",
    notes: "Offer expires Oct 10. Negotiate start date.",
    lat: 39.7392,
    lon: -104.9903,
  },
  {
    id: 4,
    company: "Harbor & Co",
    role: "Design Systems Lead",
    status: "Rejected",
    location: "Boston, MA",
    workMode: "On-site",
    date: "2026-08-18",
    salary: "",
    link: "",
    description: "Build and maintain the company-wide component library.",
    notes: "Went with internal candidate.",
    lat: 42.3601,
    lon: -71.0589,
  },
  {
    id: 5,
    company: "Quill",
    role: "Interaction Designer",
    status: "Saved",
    location: "Remote",
    workMode: "Remote",
    date: "",
    salary: "$120k–135k",
    link: "https://example.com",
    description: "Shape interactions for a writing tool. Motion and micro-interaction focus.",
    notes: "Tailor resume before applying.",
    lat: null,
    lon: null,
  },
  {
    id: 6,
    company: "Meridian Health",
    role: "Senior UX Researcher",
    status: "Screen",
    location: "Chicago, IL",
    workMode: "Hybrid",
    date: "2026-09-29",
    salary: "",
    link: "",
    description: "Plan and run mixed-methods research for patient-facing products.",
    notes: "Recruiter call Oct 6.",
    lat: 41.8781,
    lon: -87.6298,
  },
  {
    id: 7,
    company: "Coastal Transit",
    role: "Product Designer II",
    status: "Interview",
    location: "San Diego, CA",
    workMode: "On-site",
    date: "2026-09-08",
    salary: "$130k",
    link: "",
    description: "Improve rider-facing trip planning across web and kiosks.",
    notes: "Hiring manager interview done.",
    lat: 32.7157,
    lon: -117.1611,
  },
  {
    id: 8,
    company: "Lumen Retail",
    role: "UX Designer",
    status: "Ghosted",
    location: "Portland, OR",
    workMode: "Hybrid",
    date: "2026-08-05",
    salary: "",
    link: "",
    description: "E-commerce checkout and account experience.",
    notes: "No reply after 8 weeks.",
    lat: 45.5152,
    lon: -122.6784,
  },
];

export const BLANK_FORM = {
  company: "",
  role: "",
  location: "",
  workMode: "On-site" as const,
  status: "Applied" as const,
  date: "",
  salary: "",
  link: "",
  description: "",
};
